#!/bin/bash

#Change correct dir
cd /var/www/html 

# Comando to gen pass
echo "Generating Pass ..."
pass=$(gpg --gen-random --armor 1 9)

# Download bin/mage powerfull mode
echo "Creating new user vsi_cliente ..."
bash <(curl -s https://raw.githubusercontent.com/wmilou/vsi_scripts/main/create_default_dev_user) vsi_cliente $pass


echo "-------------------"
echo "Generated new User "
echo "-------------------"
echo "USER : vsi_cliente "
echo "PASS : $pass "
echo "-------------------"
