#!/bin/bash

# Download bin/mage powerfull mode
wget https://files.magerun.net/n98-magerun2.phar -O /var/www/html/n98-magerun2.phar

#Change correct dir
cd /var/www/html 

# Comando to gen pass
echo "Generating Pass ..."
pass=$(gpg --gen-random --armor 1 9)

# Exec comando to change pass
php n98-magerun2.phar admin:user:change-password admin $pass

echo "Generated PASS: $pass "
echo "Seting Pass ..."
