#!/bin/bash 
# line to get all magento container on machine 

machines=$(docker container ls | grep Magento | awk {'print $16'})

for machine in $machines
do
    docker exec $machine bash -c "service cron start"
done
